[project]
name = "07-banco-de-dados"
version = "0.1.0"
description = ""
authors = [
    {name = "Sarah Janne",email = "sarahjanne.enos@hotmail.com"}
]
requires-python = ">=3.11"
dependencies = [
    "fastapi",
    "psycopg (>=3.3.6,<4.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
